import { readFileSync, readdirSync } from 'node:fs';

/**
 * The FE/BE contract gate: every backend URL string used in
 * frontend/src/app/gateways/*.ts must exist in the committed OpenAPI
 * snapshot (docs/api/openapi.json), so a gateway drifting from a renamed
 * or removed endpoint is a test failure instead of a runtime 404.
 *
 * The snapshot is generated by the backend's OpenApiSnapshotIT —
 * regenerate it with `mvn -Dopenapi.update=true -Dtest=OpenApiSnapshotIT
 * test` BEFORE running the frontend suite.
 *
 * geocode-gateway.ts naturally contributes no literals: its URL is the
 * external OSM Nominatim service, never a backend path (the scan only
 * picks up string literals that START with `/`).
 */

/** The test runner's cwd is the frontend project root (`ng test`), and the
 * committed snapshot lives one level up, in the repo root. */
const GATEWAYS_DIR = `${process.cwd()}/src/app/gateways`;
const SNAPSHOT_PATH = `${process.cwd()}/../docs/api/openapi.json`;

/** Extracts the `/...` string literals (quotes or templates) from a source.
 *
 * Comments are stripped first: the gateway javadoc routinely writes
 * `` `update()`/`remove()` `` style prose, and scanning it yields a bogus
 * "/" path that exists in no API document. */
function stripComments(source: string): string {
  return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/[^\n]*/g, '$1');
}

function pathLiterals(source: string): string[] {
  const literals: string[] = [];
  const literal = /(['"`])(\/[^'"`]*?)\1/g;
  let match: RegExpExecArray | null;
  while ((match = literal.exec(stripComments(source))) !== null) {
    // A bare "/" is never a backend path.
    if (match[2].length > 1) {
      literals.push(match[2]);
    }
  }
  return literals;
}

/**
 * Maps a gateway URL literal onto a snapshot path:
 * `/admin/shelters/${id}/status` -> `/admin/shelters/{id}/status`
 * (a `${x}` right after a slash is a path parameter); a query string or a
 * trailing interpolation (`/admin/alerts${suffix}`) ends the static path.
 */
function toSnapshotPath(literal: string): string {
  const q = literal.indexOf('?');
  const staticPath = q === -1 ? literal : literal.slice(0, q);
  const segments: string[] = [];
  for (const part of staticPath.split('/')) {
    const open = part.indexOf('${');
    if (open === -1) {
      segments.push(part);
      continue;
    }
    if (open === 0) {
      const close = part.indexOf('}', open);
      if (close === part.length - 1) {
        segments.push(`{${part.slice(2, close)}}`);
        continue;
      }
    }
    // mixed part ("alerts${suffix}") — keep the static prefix, then stop:
    // the interpolation is a query-string suffix, not a path segment
    segments.push(part.slice(0, open));
    break;
  }
  // The split above keeps the empty leading segment for literals that start
  // with '/', so joining already yields a rooted path - prefixing another '/'
  // would produce '//account/me' and match nothing in the snapshot.
  const joined = segments.join('/');
  return joined.startsWith('/') ? joined : '/' + joined;
}

function loadSnapshot(): { paths: Record<string, unknown> } {
  try {
    return JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf8')) as {
      paths: Record<string, unknown>;
    };
  } catch {
    throw new Error(
      'docs/api/openapi.json is missing or invalid — regenerate it first: ' +
        'mvn -Dopenapi.update=true -Dtest=OpenApiSnapshotIT test',
    );
  }
}

describe('api-contract: gateway URLs vs the committed OpenAPI snapshot', () => {
  it('finds gateway files to scan (the check is not vacuous)', () => {
    const gatewayFiles = readdirSync(GATEWAYS_DIR).filter((f) => f.endsWith('-gateway.ts'));
    expect(gatewayFiles.length).toBeGreaterThanOrEqual(7);
  });

  it('every gateway URL exists in the snapshot', () => {
    const snapshotPaths = new Set(Object.keys(loadSnapshot().paths));
    const gatewayFiles = readdirSync(GATEWAYS_DIR)
      .filter((f) => f.endsWith('-gateway.ts'))
      .sort();

    const checked: string[] = [];
    for (const file of gatewayFiles) {
      const source = readFileSync(`${GATEWAYS_DIR}/${file}`, 'utf8');
      for (const literal of pathLiterals(source)) {
        const path = toSnapshotPath(literal);
        checked.push(`${file}: ${literal} -> ${path}`);
        expect(
          snapshotPaths.has(path),
          `${file} uses ${literal} (path ${path}), which is not in docs/api/openapi.json`,
        ).toBe(true);
      }
    }
    // the scan must have actually found the contract (one literal per
    // gateway method that hits the backend; ~40 today)
    expect(checked.length).toBeGreaterThanOrEqual(20);
  });
});
