import { readFileSync } from 'node:fs';

/**
 * FE/BE contract gate — the F1 class (reviews/11): the FE's RESPONSE DTO
 * field names are pinned against the committed OpenAPI snapshot
 * (docs/api/openapi.json). The sibling gate (api-contract.spec.ts) only
 * compares gateway URL literals to the snapshot's paths — a field that the
 * API never sends is invisible there: the FE reads `undefined`, and the
 * blank/NaN rendering ships with 100% green tests.
 *
 * The concrete bug this guard was written for: `AdminOccupancy` declared
 * `reportedAt` while the API sends `lastReportedAt` (both sides of the
 * contract — `ShelterDto.Occupancy` and this snapshot — agree on
 * `lastReportedAt`). The admin occupancy recency therefore always rendered
 * "just now", and the suite's fixtures encoded the same wrong name, so
 * nothing could see it.
 *
 * Direction: SUBSET. Every field the FE declares must exist in the
 * snapshot schema (a field the API never sends = the F1 class = failure).
 * The reverse is NOT asserted on purpose: the backend deliberately carries
 * fields the FE does not consume yet (`ShelterDto.provenance`,
 * `MediaAssetDto.sourceUrl`, `GuidancePostDto.alternates`/`localeFallback`),
 * and pinning equality would fail the suite on every intentional addition.
 *
 * The snapshot is generated by the backend's OpenApiSnapshotIT —
 * regenerate it with `mvn -Dopenapi.update=true -Dtest=OpenApiSnapshotIT
 * test` BEFORE running the frontend suite.
 */

/** The test runner's cwd is the frontend project root (`ng test`). */
const SNAPSHOT_PATH = `${process.cwd()}/../docs/api/openapi.json`;
const MODELS_PATH = `${process.cwd()}/src/app/core/models.ts`;

/**
 * FE interface (core/models.ts) -> OpenAPI schema name. Response shapes
 * only (the drift class: the FE reads what the API sends); request DTOs
 * are a different failure mode (a renamed request field is a loud 400,
 * not a blank cell) and are deliberately not pinned here. Projections that
 * extend a base row (detail/mine, the admin info-request exchange) pin to
 * the SAME schema the backend reuses for them.
 */
const PINNED: Record<string, string> = {
  // Fresh-window blocks (the F1 class — the admin side once read a
  // `reportedAt` the API never sends):
  ShelterOccupancy: 'Occupancy',
  AdminOccupancy: 'Occupancy',
  OpenStatusDto: 'OpenStatus',
  CommunityPulseRecentReport: 'RecentReport',
  CommunityPulseOpenClosed: 'OpenClosed',
  CommunityPulseOccupancy: 'OccupancyBands',
  CommunityPulse: 'CommunityPulse',
  // Auth / account:
  TokenResponse: 'TokenResponse',
  MeResponse: 'MeResponse',
  // Shelter rows (public list + detail + mine + admin + export):
  ShelterDto: 'ShelterDto',
  ShelterDetailDto: 'ShelterDto',
  MineShelterDto: 'ShelterDto',
  InfoRequestDto: 'InfoRequest',
  AdminInfoRequestDto: 'InfoRequest',
  AdminUserDto: 'AdminUserDto',
  AdminShelterDto: 'AdminShelterDto',
  AdminShelterReportDto: 'AdminShelterReportDto',
  AdminAuditRow: 'AdminAuditDto',
  AdminAlertRow: 'AdminAlertDto',
  DataExportShelter: 'ExportedShelter',
  DataExportResponse: 'DataExportResponse',
  // Data source, guidance, media, site texts:
  DataSourceLastImport: 'LastImport',
  DataSourceDto: 'DataSourceDto',
  GuidancePostDto: 'GuidancePostDto',
  AdminGuidancePostDto: 'AdminGuidancePostDto',
  GuidanceTranslationDto: 'GuidanceTranslationDto',
  MediaAssetDto: 'MediaAssetDto',
  SiteTextEntryDto: 'SiteTextEntry',
  ShelterReportResult: 'ShelterReportResult',
};

function loadSnapshot(): { components: { schemas: Record<string, { properties?: Record<string, unknown> }> } } {
  try {
    return JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf8')) as ReturnType<typeof loadSnapshot>;
  } catch {
    throw new Error(
      'docs/api/openapi.json is missing or invalid — regenerate it first: ' +
        'mvn -Dopenapi.update=true -Dtest=OpenApiSnapshotIT test',
    );
  }
}

/**
 * The interface body (inside its braces) by brace matching. A word
 * boundary after the name: `CommunityPulse` must not match
 * `CommunityPulseOpenClosed` (the first occurrence of the prefix).
 */
function interfaceBody(models: string, name: string): string | null {
  const marker = new RegExp(`export interface ${name}\\b`).exec(models);
  if (marker === null) return null;
  const open = models.indexOf('{', marker.index);
  let depth = 0;
  for (let i = open; i < models.length; i++) {
    if (models[i] === '{') depth++;
    else if (models[i] === '}') {
      depth--;
      if (depth === 0) return models.slice(open + 1, i);
    }
  }
  return null;
}

/**
 * Top-level field names of an interface body: one declaration per line in
 * this codebase, so a line-based scan is enough. Comments are stripped
 * first (a field mentioned in a doc comment must not count), and
 * parentheses/brackets/angle-brackets keep depth away from 0, so a nested
 * type's members could never be mistaken for the interface's own fields.
 */
function topLevelFields(body: string): string[] {
  const fields: string[] = [];
  let depth = 0;
  for (const raw of body.split('\n')) {
    const line = raw.replace(/\/\*.*?\*\//g, '').replace(/\/\/.*$/, '').trim();
    if (line.startsWith('*') || line.startsWith('/**')) continue;
    if (depth === 0) {
      const field = line.match(/^([A-Za-z_$][A-Za-z0-9_$]*)\s*[?]?:\s/);
      if (field !== null) fields.push(field[1]);
    }
    for (const ch of line) {
      if (ch === '{' || ch === '(' || ch === '<' || ch === '[') depth++;
      if (ch === '}' || ch === ')' || ch === '>' || ch === ']') depth--;
    }
  }
  return fields;
}

describe('api-contract: FE response DTO fields vs the committed OpenAPI snapshot', () => {
  it('pins every FE field of the pinned DTOs against the snapshot schemas', () => {
    const snapshot = loadSnapshot();
    const models = readFileSync(MODELS_PATH, 'utf8');

    let checkedFields = 0;
    for (const [feInterface, schemaName] of Object.entries(PINNED)) {
      const body = interfaceBody(models, feInterface);
      expect(body, `interface ${feInterface} not found in core/models.ts`).not.toBeNull();
      if (body === null) continue;
      const schema = snapshot.components.schemas[schemaName];
      expect(
        schema?.properties,
        `schema ${schemaName} not found (or has no properties) in docs/api/openapi.json — ` +
          `did the backend rename it? If so, update the PINNED table (or the FE interface).`,
      ).toBeDefined();
      const properties = Object.keys(schema.properties ?? {});
      const fields = topLevelFields(body);
      expect(
        fields.length,
        `interface ${feInterface} parsed 0 fields — the parser or the interface shape changed`,
      ).toBeGreaterThan(0);
      for (const field of fields) {
        checkedFields++;
        expect(
          properties,
          `${feInterface}.${field} is not a property of schema ${schemaName} ` +
            `(the API sends: ${properties.join(', ')}) — a field the API does not send renders ` +
            `undefined (reviews/11 F1: AdminOccupancy.reportedAt vs lastReportedAt)`,
        ).toContain(field);
      }
    }
    // The pin must actually cover the contract (a parser regression that
    // yields zero fields per interface is caught above; this catches the
    // table being silently emptied).
    expect(checkedFields).toBeGreaterThanOrEqual(100);
  });

  it('the admin and public occupancy blocks pin to the SAME wire schema', () => {
    // The whole F1 class in one assertion: the admin list's occupancy block
    // and the public list's occupancy block are the same backend record
    // (ShelterDto.Occupancy) — if the FE ever declares them with different
    // field names again, this table (and the field loop above) fails.
    expect(PINNED['AdminOccupancy']).toBe('Occupancy');
    expect(PINNED['ShelterOccupancy']).toBe('Occupancy');
  });
});
