package ee.sheltermap.guidance;

import ee.sheltermap.domain.MediaAsset;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.net.InetAddress;
import java.net.URI;
import java.net.UnknownHostException;
import java.time.Clock;
import java.time.Duration;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.function.LongSupplier;

/**
 * Imports a remote image into the media library (guidance-hero-import):
 * the admin pastes an http(s) URL into a post's hero field, and this
 * service — called at SAVE time (create and update, draft or published
 * alike) — downloads, validates and stores the image under a generated
 * name, returning the asset the post links as its hero.
 *
 * <p>The import runs in its OWN transaction (REQUIRES_NEW): a failure
 * anywhere rolls back the asset row (the just-written file is removed by
 * the store step) and propagates to the save, which STORES THE POST
 * ANYWAY — a failed import never blocks a save; the save surfaces the
 * error against the hero field and keeps the URL for a retry on the next
 * save, the hero falling back to the request's library reference or the
 * previously stored one. A success commits the library row before the
 * caller links it as the hero.
 *
 * <p>The walk and its guards, in order (each pinned by a test):
 * <ol>
 *   <li><b>Scheme allowlist</b> (guard 1): {@code http}/{@code https}
 *       only — {@code file:}, {@code ftp:}, {@code gopher:}, {@code data:},
 *       {@code javascript:} and anything else is refused before any I/O;</li>
 *   <li><b>No credentials in the URL</b> (guard 2): a {@code user:pass@}
 *       host is refused — otherwise the pasted credentials would be sent
 *       to the remote host as an {@code Authorization: Basic} header;</li>
 *   <li><b>Address policy</b> (guard 3, the SSRF core): the host is
 *       resolved and the fetch is refused when ANY resolved address is
 *       loopback, private (RFC 1918), link-local (169.254.0.0/16, which
 *       includes the cloud-metadata 169.254.169.254, or fe80::/10),
 *       unique-local (fc00::/7, which includes the AWS metadata form
 *       fd00:ec2::254), multicast or unspecified. The target of EVERY
 *       redirect hop is re-resolved and re-checked by the same method
 *       BEFORE it is fetched — validating only the first URL is
 *       insufficient, because a PUBLIC host can answer a 302 pointing at
 *       {@code http://127.0.0.1/…} or the metadata service; the hop cap
 *       is 3, like the geo resolver, and a redirect that changes to a
 *       non-http(s) scheme is refused without fetching;</li>
 *   <li><b>Size cap while reading</b> (guard 4): the fetch client
 *       enforces {@code app.media.max-bytes} mid-stream and aborts past
 *       it (413, the upload path's vocabulary) — never buffered
 *       unboundedly and checked afterwards;</li>
 *   <li><b>Timeouts</b> (guard 5): connect + exchange timeouts in the
 *       client, a read-stall watchdog in the client, and a wall-clock
 *       budget for the whole walk (monotonic deadline checked before
 *       every hop — a stalled upstream cannot pin the request thread
 *       past the budget, the geo resolver's idiom);</li>
 *   <li><b>Content validation</b> (guard 6): the bytes go through
 *       {@link MediaImageInspector}; anything that is not a readable
 *       JPEG/PNG/WebP is refused (400, the upload path's vocabulary);</li>
 *   <li><b>Pixel cap</b> (guard 7): the header dimensions must not
 *       exceed the per-side maximum — a few-kilobyte file can claim a
 *       canvas that decodes to a multi-gigabyte bitmap, so the dimensions
 *       are capped, not just the byte size.</li>
 * </ol>
 *
 * <p><b>Why this is safe to serve:</b> the stored file's name is
 * generated by the server (32 hex + the sniffed extension — the remote
 * filename never touches a path), and the asset's content type — and the
 * {@code Content-Type} of the public serving endpoint — come from the
 * SNIFFED bytes, not the remote header and not the remote filename. A
 * script or a polyglot therefore cannot be stored or served as an image:
 * only bytes the inspector reads as JPEG/PNG/WebP ever reach the library.
 * The same gate is extended to the thumbnail derivatives (rendered
 * from the validated bytes at store time and re-gated by
 * {@link MediaImageInspector} before they are written beside the
 * original — a derivative that fails the gate fails the import).
 */
@Service
public class HeroImageImportService {

    /** At most this many redirect hops are followed (the geo resolver's cap). */
    static final int MAX_REDIRECT_HOPS = 3;

    /** Overall wall-clock budget for the whole walk (the geo resolver's 10 s). */
    static final Duration DEFAULT_BUDGET = Duration.ofSeconds(10);

    /**
     * The documented pixel cap (per side, guard 7): 10000 px means the
     * largest importable image is 10000×10000 = 100 Mpx ≈ 400 MiB of
     * BGRA when decoded. Far above anything a guidance hero needs
     * (the page scales it to a fraction of a megapixel); far below a
     * decompression-bomb memory-exhaustion vector.
     */
    static final int DEFAULT_MAX_SIDE = 10_000;

    /** The extension implied by the SNIFFED type — one shared table, owned by the inspector. */
    private static final Map<String, String> EXTENSION_BY_TYPE =
            MediaImageInspector.EXTENSION_BY_TYPE;

    private final HeroImageFetchClient fetchClient;
    private final HeroAddressResolver addresses;
    private final MediaStorage storage;
    private final MediaAssetRepository mediaAssets;
    private final Clock clock;
    /** The size cap — the SAME {@code app.media.max-bytes} as uploads. */
    private final long maxBytes;
    private final Duration budget;
    private final int maxSide;
    private final LongSupplier monotonicNanos;

    @Autowired
    public HeroImageImportService(HeroImageFetchClient fetchClient,
                                  HeroAddressResolver addresses,
                                  MediaStorage storage,
                                  MediaAssetRepository mediaAssets,
                                  Clock clock,
                                  @Value("${app.media.max-bytes:5242880}") long maxBytes,
                                  @Value("${app.media.import-budget:10s}") Duration budget,
                                  @Value("${app.media.import-max-side:10000}") int maxSide) {
        this(fetchClient, addresses, storage, mediaAssets, clock, maxBytes, budget, maxSide,
                System::nanoTime);
    }

    /** Test seam — explicit budget and monotonic nanosecond clock. */
    HeroImageImportService(HeroImageFetchClient fetchClient,
                           HeroAddressResolver addresses,
                           MediaStorage storage,
                           MediaAssetRepository mediaAssets,
                           Clock clock,
                           long maxBytes,
                           Duration budget,
                           int maxSide,
                           LongSupplier monotonicNanos) {
        this.fetchClient = Objects.requireNonNull(fetchClient, "fetchClient");
        this.addresses = Objects.requireNonNull(addresses, "addresses");
        this.storage = Objects.requireNonNull(storage, "storage");
        this.mediaAssets = Objects.requireNonNull(mediaAssets, "mediaAssets");
        this.clock = Objects.requireNonNull(clock, "clock");
        this.maxBytes = maxBytes;
        this.budget = budget;
        this.maxSide = maxSide;
        this.monotonicNanos = Objects.requireNonNull(monotonicNanos, "monotonicNanos");
    }

    /**
     * Fetches, validates and stores the image at {@code url}.
     *
     * <p>Runs in its OWN transaction ({@code REQUIRES_NEW}): a failure
     * anywhere rolls back the asset row WITHOUT touching the caller's
     * save, which stores the post regardless and surfaces the error;
     * a success commits the library row before the caller links it as
     * the hero. The network I/O is bounded by the walk budget, so the
     * transaction is held for at most that long (an admin-only
     * operation, by design).
     *
     * @param adminId  the acting admin — stamped on the asset as uploader
     * @param url      the admin-supplied URL (re-validated here — the
     *                 service is the authority, the request bean is not)
     * @return the stored asset (id assigned)
     * @throws HeroImportRefusedException     scheme/credentials/address
     *                                        policy, a disallowed redirect,
     *                                        the hop cap, or a remote 4xx
     * @throws HeroImportUnreachableException DNS failure, connect/read
     *                                        timeout or stall, network
     *                                        failure, a remote 5xx, or the
     *                                        walk budget
     * @throws MediaTooLargeException         the body exceeded the cap
     * @throws UnsupportedImageException      not a readable JPEG/PNG/WebP,
     *                                        or over the pixel cap
     */
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public MediaAsset importHero(long adminId, String url) {
        URI current = validatedEntry(url);
        long deadlineNanos = monotonicNanos.getAsLong() + budget.toNanos();

        for (int hop = 0; hop <= MAX_REDIRECT_HOPS; hop++) {
            // The walk is over budget — a stalled upstream, not bad input.
            if (monotonicNanos.getAsLong() > deadlineNanos) {
                throw new HeroImportUnreachableException(
                        "The hero image fetch exceeded its " + budget + " wall-clock budget");
            }
            // Guard 3: the host of the URL ABOUT TO BE FETCHED is resolved
            // and every resolved address classified — on the FIRST url and
            // on every redirect target (the hop loop re-enters here for
            // each validated target, so no hop is ever fetched unchecked).
            assertHostAllowed(current);
            HeroImageFetchClient.FetchedImage response = fetchClient.fetch(current.toString(), maxBytes);
            if (response.isRedirect()) {
                // Re-validate the hop target BEFORE fetching it: a
                // malformed Location, a non-http(s) scheme change or a
                // user:pass@ target is a refusal, never a fetch. The
                // target's ADDRESS is checked on the next iteration, the
                // moment before its fetch.
                current = validatedHopTarget(current, response.location());
                continue;
            }
            return store(adminId, url, response);
        }
        // The walk is full and the last response was still a redirect.
        throw new HeroImportRefusedException("The hero image URL took more than "
                + MAX_REDIRECT_HOPS + " redirects");
    }

    // ------------------------------------------------------------- guards

    /**
     * The entry URL, validated (guards 1–2). Malformed input, a
     * non-http(s) scheme, a missing host or embedded credentials are all
     * refusals — nothing is fetched.
     */
    private static URI validatedEntry(String url) {
        String trimmed = url == null ? "" : url.trim();
        URI uri;
        try {
            uri = URI.create(trimmed);
        } catch (IllegalArgumentException e) {
            throw new HeroImportRefusedException("The hero image URL is not a valid URL");
        }
        return checkedUrlShape(uri);
    }

    /**
     * The shared URL shape policy for the entry and every redirect
     * target.
     */
    private static URI checkedUrlShape(URI uri) {
        // Guard 1 — scheme allowlist: http/https ONLY. file: would read
        // local files off the server, gopher:/data:/javascript: are
        // protocol-injection vectors — everything without an http(s)
        // scheme is refused outright, before any I/O.
        String scheme = uri.getScheme();
        if (!"http".equalsIgnoreCase(scheme) && !"https".equalsIgnoreCase(scheme)) {
            throw new HeroImportRefusedException("The hero image URL must use http or https (got '"
                    + (scheme == null ? "<none>" : scheme) + "')");
        }
        if (uri.getHost() == null || uri.getHost().isBlank()) {
            throw new HeroImportRefusedException("The hero image URL must name a host");
        }
        // Guard 2 — no credentials: a user:pass@ URL would transmit the
        // pasted credentials to the remote host as an Authorization:
        // Basic header (the same leak the geo resolver's entry
        // normalization prevents) — refused, never fetched.
        if (uri.getUserInfo() != null) {
            throw new HeroImportRefusedException(
                    "The hero image URL must not carry credentials (user:pass@)");
        }
        return uri;
    }

    /**
     * Guard 3 — resolves {@code uri}'s host and refuses the fetch when
     * ANY resolved address is disallowed (see {@link HeroAddressPolicy}).
     */
    private void assertHostAllowed(URI uri) {
        List<InetAddress> resolved;
        try {
            resolved = addresses.resolve(uri.getHost());
        } catch (UnknownHostException e) {
            throw new HeroImportUnreachableException(
                    "Could not resolve the hero image host '" + uri.getHost() + "'");
        }
        for (InetAddress address : resolved) {
            String reason = HeroAddressPolicy.disallowedReason(address);
            if (reason != null) {
                throw new HeroImportRefusedException("The hero image URL resolves to "
                        + address.getHostAddress() + " (" + reason + ") — loopback, private, "
                        + "link-local, unique-local, multicast and cloud-metadata addresses "
                        + "are not importable");
            }
        }
    }

    /**
     * Resolves a {@code Location} header against the URL that carried it
     * and re-validates the result (guards 1–2 on the TARGET).
     *
     * <p>Why validating only the first URL is insufficient: a PUBLIC host
     * (one that passed the address policy) can answer a redirect pointing
     * at {@code http://127.0.0.1/admin} or the cloud-metadata service —
     * the fetch would then hit the internal address even though the URL
     * the admin pasted was innocent. Every hop target is therefore
     * re-validated here (scheme + credentials) and its ADDRESS is
     * re-checked by {@link #assertHostAllowed} on the next iteration,
     * before it is fetched. A scheme change to non-http(s) is refused;
     * an http→https upgrade is legitimate and allowed (unlike the geo
     * resolver's pinned same-scheme rule, which serves its whitelist
     * entry, not an arbitrary host).
     */
    private static URI validatedHopTarget(URI current, String location) {
        URI target;
        try {
            target = current.resolve(location);
        } catch (IllegalArgumentException e) {
            throw new HeroImportRefusedException("A redirect target was not a valid URL");
        }
        return checkedUrlShape(target);
    }

    // ------------------------------------------------------------- store

    /**
     * The terminal response: status and body checks, the content and
     * pixel gates (guards 6–7), the in-memory derivative render (a
     * derivative that fails the content gate fails the import before
     * anything touches disk), then the store — original file first, row
     * second, derivative files last, with the orphan cleanup of the
     * upload path.
     */
    private MediaAsset store(long adminId, String sourceUrl,
                             HeroImageFetchClient.FetchedImage response) {
        byte[] bytes = requireSuccessfulResponse(response);
        MediaImageInspector.ImageInfo info = validateImportedBytes(bytes);

        String extension = EXTENSION_BY_TYPE.get(info.contentType().toLowerCase(Locale.ROOT));
        if (extension == null) {
            // Defensive: the inspector only answers with the three types,
            // but a drifted implementation must not mint an
            // extensionless public name (the upload path's guard).
            throw new UnsupportedImageException("Unsupported image type: " + info.contentType());
        }

        // The thumbnail derivatives, rendered IN MEMORY before
        // anything touches disk: a derivative that fails the content
        // gate fails the import HERE (the post stays a DRAFT — the
        // acceptance rule). An undecodable body (or a WebP original —
        // no JDK decoder) simply yields NO derivatives: the original is
        // still stored and served.
        List<MediaDerivatives.RenderedDerivative> derivatives = renderDerivativesStrict(info, bytes);

        // Every validation step passed — only now do the bytes touch disk
        // (file first, row second, the upload path's order).
        MediaStorage.StoredFile stored = storage.store(bytes, extension);
        try {
            MediaAsset asset = mediaAssets.save(MediaAsset.create(
                    stored.storedFilename(), null, info.contentType(),
                    info.width(), info.height(), bytes.length,
                    adminId, clock.instant(), sourceUrl));
            // The derivative files join after the row: a row failure
            // below removes the original AND the derivatives (no
            // orphan); a derivative WRITE failure after the row only
            // skips the width (the srcset is built from what exists).
            storeDerivativeFiles(stored.storedFilename(), derivatives);
            return asset;
        } catch (RuntimeException ex) {
            // The file is on disk but the row could not be stored: remove
            // the just-written file AND the derivatives written so far so
            // a failed import leaves no orphan (the row rolls back with
            // the transaction anyway).
            storage.deleteWithDerivatives(stored.storedFilename());
            throw ex;
        }
    }

    /**
     * The response-status gate: a 2xx with a non-empty body is the only
     * answer that proceeds. A remote 5xx is a deterministic server-side
     * failure upstream — transient, a retry may succeed → the 502
     * vocabulary; a 4xx is a broken URL, no retry will fix it → 400;
     * an empty body is a refusal.
     */
    private static byte[] requireSuccessfulResponse(HeroImageFetchClient.FetchedImage response) {
        int status = response.status();
        if (status < 200 || status >= 300) {
            if (status >= 500) {
                throw new HeroImportUnreachableException("The host serving the hero image "
                        + "answered HTTP " + status + " (a retry may succeed)");
            }
            throw new HeroImportRefusedException("The hero image URL answered HTTP " + status
                    + " (the URL is broken — no retry will fix it)");
        }
        byte[] bytes = response.body();
        if (bytes == null || bytes.length == 0) {
            throw new HeroImportRefusedException("The hero image URL answered with an empty body");
        }
        return bytes;
    }

    /**
     * Guards 6 and 7 on the fetched body — content validation, then the
     * pixel cap.
     *
     * <p>Guard 6 is THE whole reason this feature is safe: (1) the
     * stored file's name is generated by the server (32 hex + the
     * sniffed extension — the remote filename never touches a path),
     * (2) the bytes are sniffed by magic (NEVER the remote Content-Type
     * header, which a hostile or broken host can set to anything — a
     * text file served as image/png fails here), and (3) the stored
     * asset's content_type — and the Content-Type the public serving
     * endpoint answers with — come from that sniffed type. A script or
     * a polyglot therefore cannot be stored or served as an image: only
     * bytes the inspector reads as JPEG/PNG/WebP ever reach the library.
     *
     * <p>Guard 7 — the decompression-bomb cap. The dimensions come from
     * the image HEADER, not the byte size: a few-kilobyte file can claim
     * a 30000×30000 canvas that decodes to a multi-gigabyte bitmap the
     * first time anything scales or decodes it. Capping either side at
     * 10000 px ({@code app.media.import-max-side}) bounds the decodable
     * bitmap at ~400 MiB — far above any hero's needs, far below memory
     * exhaustion.
     */
    private MediaImageInspector.ImageInfo validateImportedBytes(byte[] bytes) {
        MediaImageInspector.ImageInfo info = MediaImageInspector.inspect(bytes)
                .orElseThrow(() -> new UnsupportedImageException(
                        "The hero image URL does not serve a readable JPEG, PNG or WebP image"));
        if (info.width() > maxSide || info.height() > maxSide) {
            throw new UnsupportedImageException("The hero image is " + info.width() + "×"
                    + info.height() + " pixels — the import limit is " + maxSide
                    + " pixels per side");
        }
        return info;
    }

    /**
     * The import-path render step (strict gate): every derivative
     * the original can serve (renderable format only — no WebP;
     * guard 7 already bounded the sides, re-checked here defensively;
     * no upscale), each rendered byte sequence re-gated by the SAME
     * inspector as the original (guard 6 extended to the encoder's
     * output). A gate failure THROWS — the acceptance rule: a
     * derivative that fails validation fails the import and the post
     * stays a DRAFT. Package-visible for the tests (the rule is
     * asserted on this seam).
     */
    List<MediaDerivatives.RenderedDerivative> renderDerivativesStrict(
            MediaImageInspector.ImageInfo info, byte[] bytes) {
        if (!MediaDerivatives.isRenderable(info.contentType())) {
            return List.of(); // WebP: no JDK decoder — the slots render the original
        }
        if (info.width() > maxSide || info.height() > maxSide) {
            return List.of(); // guard 7 already refused such an import; defensive
        }
        return MediaDerivatives.renderAll(
                info.contentType(), info.width(), info.height(), bytes, false);
    }

    /**
     * The import-path write step: the rendered derivative files
     * beside the original. A per-width write failure only skips the
     * width (the original + the row stand; the srcset lists what
     * exists) — a disk failure is not a validation failure.
     */
    private void storeDerivativeFiles(String storedFilename,
                                      List<MediaDerivatives.RenderedDerivative> derivatives) {
        for (MediaDerivatives.RenderedDerivative derivative : derivatives) {
            try {
                storage.storeDerivative(storedFilename, derivative.width(), derivative.bytes());
            } catch (RuntimeException ex) {
                // skip the width — the original stands
            }
        }
    }
}
