package ee.sheltermap.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.media.Content;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import org.springdoc.core.customizers.OpenApiCustomizer;

import java.util.Map;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * The OpenAPI document assembly: metadata, the bearer security
 * scheme, the uniform error contract and the group split.
 *
 * <p>The document is a complete map of the attack surface, so it is
 * dev-gated twice: {@code SPRINGDOC_ENABLED} defaults to false in both
 * {@code application.yml} files, and {@link ApiDocsGuard} refuses to boot
 * on a non-dev/test profile when the flag is set (a copied dev {@code .env}
 * must never publish the admin API map). The security chain additionally
 * permits {@code /v3/api-docs/**} + {@code /swagger-ui/**} only under
 * dev/test.
 *
 * <p>Metadata sources this document points at:
 * {@code context-and-tasks/05-shelter-api.puml} (the read contract, cited by
 * {@code ShelterDto}), the README "API" section and
 * {@code docs/whitepaper.md}. The committed snapshot is
 * {@code docs/api/openapi.json} (generated by
 * {@code OpenApiSnapshotIT}, regenerated with {@code -Dopenapi.update=true}).
 */
@Configuration
public class OpenApiConfig {

    /** The one bearer scheme — the name every {@code security} entry uses. */
    static final String BEARER_AUTH = "bearerAuth";

    @Bean
    public OpenAPI openShelterOpenApi(
            @Value("${spring.application.version:0.0.1-SNAPSHOT}") String version) {
        return new OpenAPI()
                .info(new Info()
                        .title("OpenShelter API")
                        // Read from the build, not hand-typed (the fallback
                        // tracks the POM version 0.0.1-SNAPSHOT).
                        .version(version)
                        .description("The machine-readable contract of the OpenShelter "
                                + "backend. Companion to the human contracts: "
                                + "context-and-tasks/05-shelter-api.puml (the read "
                                + "contract), the README 'API' section and "
                                + "docs/whitepaper.md. Served at /v3/api-docs in "
                                + "dev/test only (SPRINGDOC_ENABLED); the committed "
                                + "snapshot is docs/api/openapi.json. Every non-2xx "
                                + "response carries the uniform ErrorResponse body.")
                        .contact(new Contact()
                                .name("Aleks Bratsun (project owner)")
                                .email("aleks.bratsun@reaktiiv.com"))
                        .license(new License().name("MIT")))
                // One relative server: the frontend dev server proxies to the
                // backend, and an absolute dev host would silently rot in the
                // committed snapshot.
                .servers(List.of(new Server().url("/")))
                .components(new Components()
                        // The uniform error body, published ONCE (D2) — the
                        // customizer below points every operation's error
                        // responses at this single schema. Keep in sync with
                        // the ErrorResponse record (the one uniform error
                        // shape of the whole API).
                        .addSchemas("ErrorResponse", new Schema<>()
                                .type("object")
                                .description("The one uniform error shape for "
                                        + "the whole API — every error response "
                                        + "(validation, 401, 403, 404, 429, 500) "
                                        + "is this record.")
                                .addProperties("timestamp",
                                        new Schema<>().type("string")
                                                .format("date-time")
                                                .description("When the error "
                                                        + "occurred."))
                                .addProperties("status", new Schema<>()
                                        .type("integer").format("int32")
                                        .description("The HTTP status code."))
                                .addProperties("error", new Schema<>()
                                        .type("string")
                                        .description("The HTTP reason phrase."))
                                .addProperties("message", new Schema<>()
                                        .type("string")
                                        .description("A human-readable detail."))
                                .addProperties("path", new Schema<>()
                                        .type("string")
                                        .description("The request path that "
                                                + "failed.")))
                        .addSecuritySchemes(BEARER_AUTH, new SecurityScheme()
                                .name(BEARER_AUTH)
                                .type(SecurityScheme.Type.HTTP)
                                .scheme("bearer")
                                .bearerFormat("JWT")
                                .description("The `Authorization: Bearer <accessToken>` "
                                        + "header read by the JWT filter. A valid token "
                                        + "of a SUSPENDED account authenticates nothing "
                                        + "(fresh per-request DB lookup — the DB is the "
                                        + "truth, never a token claim).")))
                // The global requirement: everything is bearer-authenticated
                // UNLESS an operation opts out with an empty
                // @SecurityRequirements (the genuinely public operations).
                .security(List.of(new SecurityRequirement().addList(BEARER_AUTH)));
    }

    /**
     * The uniform error contract, published once (D2): the app guarantees
     * ONE error shape ({@code ErrorResponse} — every error response is that
     * record), so the document attaches a reusable response per status to
     * every operation that does not already declare that code with its own
     * precise wording. Deliberately a superset: the point is the shared
     * SHAPE, and per-operation {@code @ApiResponse} entries (which are never
     * overwritten) carry the endpoint-specific meaning.
     */
    @Bean
    public OpenApiCustomizer uniformErrorResponseCustomizer() {
        return openApi -> openApi.getPaths().forEach((path, pathItem) ->
                pathItem.readOperationsMap().forEach((method, operation) -> {
                    attachIfAbsent(operation, "400",
                            "Validation failure — the uniform error body.");
                    attachIfAbsent(operation, "401",
                            "Missing/invalid/expired bearer token, or a suspended account "
                                    + "whose tokens authenticate nothing.");
                    attachIfAbsent(operation, "403",
                            "Authenticated but not allowed (admin kind, verified account "
                                    + "or authorship).");
                    attachIfAbsent(operation, "404",
                            "Unknown resource id — the uniform error body.");
                    attachIfAbsent(operation, "409",
                            "Conflict (duplicate or forbidden state) — the uniform error body.");
                    attachIfAbsent(operation, "429",
                            "Rate limit / report throttle exceeded — Retry-After in seconds.");
                    attachIfAbsent(operation, "500",
                            "Unexpected server error — the uniform error body.");
                }));
    }

    /**
     * The machine-readable admin marker (SW-E): springdoc does not surface a
     * standalone method-level {@code @Extension}, so the marker is attached
     * to every {@code /admin/**} operation here instead - in the
     * {@code {"value": "true"}} shape the original
     * {@code @ExtensionProperty} declaration specified. One rule, derived
     * from the same route prefix the authorization matcher enforces, so the
     * published contract cannot drift from the security boundary.
     */
    @Bean
    public OpenApiCustomizer adminOnlyExtensionCustomizer() {
        return openApi -> openApi.getPaths().forEach((path, pathItem) -> {
            if (path.startsWith("/admin/")) {
                pathItem.readOperationsMap().forEach((method, operation) ->
                        operation.addExtension("x-admin-only", Map.of("value", "true")));
            }
        });
    }

    /**
     * The group split (D3): public / account / admin. NO group matches
     * {@code /dev/**} (the guarded relays are meant to be invisible — and
     * both controllers are {@code @Hidden} too, so even the root document
     * cannot absorb them) and none matches {@code /actuator/**}
     * ({@code show-actuator: false}).
     */
    @Bean
    public GroupedOpenApi publicGroup() {
        return GroupedOpenApi.builder()
                .group("public")
                .pathsToMatch("/api/shelters/**", "/api/data-source", "/auth/**")
                .build();
    }

    @Bean
    public GroupedOpenApi accountGroup() {
        return GroupedOpenApi.builder()
                .group("account")
                .pathsToMatch("/account/**", "/verify/**", "/api/shelters/mine",
                        "/api/geo/resolve")
                .build();
    }

    @Bean
    public GroupedOpenApi adminGroup() {
        return GroupedOpenApi.builder()
                .group("admin")
                .pathsToMatch("/admin/**")
                .build();
    }

    private static void attachIfAbsent(Operation operation,
                                       String code, String description) {
        if (operation.getResponses() == null) {
            operation.setResponses(new ApiResponses());
        }
        // A $ref body: sibling keywords such as format are ignored by the
        // OpenAPI 3.0 spec, so only the reference is set here.
        operation.getResponses().putIfAbsent(code,
                new ApiResponse()
                        .description(description)
                        .content(new Content().addMediaType("application/json",
                                new MediaType().schema(new Schema<>()
                                        .$ref("#/components/schemas/ErrorResponse")))));
    }
}
